### ISSUE TITLE
오류수정 페이지 내용 추가 요청

### ISSUE THREAD

**Issue by Root-kjh** [dextto/book-nestjs-backend#2]
page. 141의 checkUserExists 부분에서 user !== undefined로 유저가 존재하는지를 검사하는데, 해당 부분에서 오류가 발생합니다.
user !== null 로 구문 수정 시 정상동작 하고, 깃헙의 예제 코드에서도 수정되어 있는것을 확인할 수 있습니다.

```
    private async checkUserExists(emailAddress: string){
        const user = await this.userRepository.findOne({
            where: { email: emailAddress }
        });
        return user !== null;
    }
```

**Comment by Root-kjh** [comment]
page. 238의 HealthCheckController를 app module에 추가하는 부분에서 오류가 발생합니다.
책에서는 providers에 추가하는 것으로 되어있지만, controllers에 추가되어야합니다.
```
  ...
  controllers: [HealthCheckController],
  providers: [],
  ...
})
```

**Comment by dextto** [comment]
@Root-kjh 피드백 감사합니다. 👍 증쇄시 반영하겠습니다.

참고로, findOne의 리턴값은 typeorm 0.3을 반영하는 과정에서 누락되었네요.

**Comment by dextto** [comment]
FixError.md에 반영하였습니다. :)
