### ISSUE TITLE
8장 ormconfig.ts 관련 질문

### ISSUE THREAD

**Issue by seolcoding** [dextto/book-nestjs-backend#3]
선생님 안녕하세요! 집필하신 책으로 즐겁고 열심히 공부하고 있는 독자입니다.
좋은 교재 만들어주셔서 감사합니다.

8장 학습하던 중 오류라고 생각되는 부분이 있어 질문드립니다.
p.146 ormconfig.ts 부분에서

`migrations: [__dirname + '/**/migrations/*.js']`에 
*.js파일만 명시해서
*.ts로 생성되는 마이그레이션 파일을 인식못하는 오류가 있었습니다.

혹시 아래와 같이 변경해도 괜찮을지 질문드립니다.
`migrations: [__dirname + '/**/migrations/*.{js, ts}']`

**Comment by dextto** [comment]
그렇군요! 제가 책을 집필하던 환경에서는 문제가 되지 않았는데 이상하군요. 
하지만 말씀하신 대로 수정해도 전혀 문제되지 않을것 같아요!! 👍

**Comment by seolcoding** [comment]
답변 감사합니다. 
집필당시에 문제가 없으셨다는 답변을 보고 제 환경에서 뭐가 잘못됐는지 문제점을 찾아봤습니다.

제 환경에서는 `tsc -w`를 켜놓지 않아서 마이그레이션 파일이 .js로 컴파일이 되지 않아 
아래와 같은 문제가 발생했던 것 같습니다.
![image](https://user-images.githubusercontent.com/47937914/232483720-3dd8f46b-dae1-4459-9de4-e9c27aa20c2d.png)


그런데 tsc -w 로 항상 컴파일을 하고 있는 중에 `*.{js, ts}`로 설정하면
다음과 같은 에러가 발생합니다.
![image](https://user-images.githubusercontent.com/47937914/232482832-5a01136a-e659-4f30-8b61-b7b378176b0f.png)

따라서 컴파일을 자동으로 수행하는 환경이라면 `*.{js}`,
아니라면 `*.{ts}`를 선택하는 것이 좋겠다는 생각이 들었습니다.

감사합니다!!
